function phenoSites = importfile2(filename, startRow, endRow)
%IMPORTFILE2 Import numeric data from a text file as a matrix.
%   PHENOSITES = IMPORTFILE2(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   PHENOSITES = IMPORTFILE2(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   phenoSites = importfile2('phenoSites.txt', 2, 545);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/06/20 13:26:18

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,3,4,9,10,22,23,24,25,26,27,32,33,34]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end

dateFormatIndex = 1;
blankDates = cell(1,size(raw,2));
anyBlankDates = false(size(raw,1),1);
invalidDates = cell(1,size(raw,2));
anyInvalidDates = false(size(raw,1),1);
for col=[7,8]% Convert the contents of columns with dates to MATLAB datetimes using the specified date format.
    try
        dates{col} = datetime(dataArray{col}, 'Format', 'yyyy-MM-dd', 'InputFormat', 'yyyy-MM-dd'); %#ok<AGROW>
    catch
        try
            % Handle dates surrounded by quotes
            dataArray{col} = cellfun(@(x) x(2:end-1), dataArray{col}, 'UniformOutput', false);
            dates{col} = datetime(dataArray{col}, 'Format', 'yyyy-MM-dd', 'InputFormat', 'yyyy-MM-dd'); %#ok<AGROW>
        catch
            dates{col} = repmat(datetime([NaN NaN NaN]), size(dataArray{col})); %#ok<AGROW>
        end
    end
    
    dateFormatIndex = dateFormatIndex + 1;
    blankDates{col} = dataArray{col} == '';
    anyBlankDates = blankDates{col} | anyBlankDates;
    invalidDates{col} = isnan(dates{col}.Hour) - blankDates{col};
    anyInvalidDates = invalidDates{col} | anyInvalidDates;
end
dates = dates(:,[7,8]);
blankDates = blankDates(:,[7,8]);
invalidDates = invalidDates(:,[7,8]);

%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [2,3,4,9,10,22,23,24,25,26,27,32,33,34]);
rawStringColumns = string(raw(:, [1,5,6,11,12,13,14,15,16,17,18,19,20,21,28,29,30,31,35]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
for catIdx = [2,3,4,5,6,8,9,10,11,12,13,16,17,18,19]
    idx = (rawStringColumns(:, catIdx) == "<undefined>");
    rawStringColumns(idx, catIdx) = "";
end

%% Create output variable
phenoSites = table;
phenoSites.site = rawStringColumns(:, 1);
phenoSites.lat = cell2mat(rawNumericColumns(:, 1));
phenoSites.lon = cell2mat(rawNumericColumns(:, 2));
phenoSites.elev = cell2mat(rawNumericColumns(:, 3));
phenoSites.contact1 = categorical(rawStringColumns(:, 2));
phenoSites.contact2 = categorical(rawStringColumns(:, 3));
phenoSites.date_start = dates{:, 1};
phenoSites.date_end = dates{:, 2};
phenoSites.nimage = cell2mat(rawNumericColumns(:, 4));
phenoSites.tzoffset = cell2mat(rawNumericColumns(:, 5));
phenoSites.active = categorical(rawStringColumns(:, 4));
phenoSites.infrared = categorical(rawStringColumns(:, 5));
phenoSites.method = categorical(rawStringColumns(:, 6));
phenoSites.site_description = rawStringColumns(:, 7);
phenoSites.group = categorical(rawStringColumns(:, 8));
phenoSites.camera_description = categorical(rawStringColumns(:, 9));
phenoSites.camera_orientation = categorical(rawStringColumns(:, 10));
phenoSites.site_type = categorical(rawStringColumns(:, 11));
phenoSites.flux_data = categorical(rawStringColumns(:, 12));
phenoSites.flux_networks = categorical(rawStringColumns(:, 13));
phenoSites.flux_sitenames = rawStringColumns(:, 14);
phenoSites.MAT_site = cell2mat(rawNumericColumns(:, 6));
phenoSites.MAP_site = cell2mat(rawNumericColumns(:, 7));
phenoSites.MAT_daymet = cell2mat(rawNumericColumns(:, 8));
phenoSites.MAP_daymet = cell2mat(rawNumericColumns(:, 9));
phenoSites.MAT_worldclim = cell2mat(rawNumericColumns(:, 10));
phenoSites.MAP_worldclim = cell2mat(rawNumericColumns(:, 11));
phenoSites.dominant_species = rawStringColumns(:, 15);
phenoSites.primary_veg_type = categorical(rawStringColumns(:, 16));
phenoSites.secondary_veg_type = categorical(rawStringColumns(:, 17));
phenoSites.koeppen_geiger = categorical(rawStringColumns(:, 18));
phenoSites.ecoregion = cell2mat(rawNumericColumns(:, 12));
phenoSites.wwf_biome = cell2mat(rawNumericColumns(:, 13));
phenoSites.landcover_igbp = cell2mat(rawNumericColumns(:, 14));
phenoSites.site_acknowledgements = categorical(rawStringColumns(:, 19));

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% phenoSites.date_start=datenum(phenoSites.date_start);
% phenoSites.date_end=datenum(phenoSites.date_end);

